<a href="https://colab.research.google.com/github/Maruf-shiab/Deep-Learning/blob/main/DeepLearning_or_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd



In [2]:
class Perceptron :
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3)*1e-4
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self,Input,Weights):
    z=np.dot(Input,Weights)
    return np.where(z>0,1,0)

  def fit(self,X,Y):
    self.X = X
    self.Y = Y

    X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
    print(f"X with bias: \n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch >> {epoch}")
      y_hat = self.activationFunction(X_with_bias,self.weights)
      print(f"predicted value after forward pass: \n{y_hat}")

      self.error = self.Y - y_hat
      print(f"error: \n{self.error}")
      self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
      print(f"updated weights after epoch: {epoch}/{self.epochs}: \n{self.weights}")


In [7]:
Data ={
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

Data_Or=pd.DataFrame(Data)
X=Data_Or.drop("y",axis=1)
Y=Data_Or['y']


,y
0,0
1,1
2,1
3,1


In [8]:
model=Perceptron(eta=0.1,epochs=10)
model.fit(X,Y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 0
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 0/10: 
[7.84003612e-05 9.96378718e-05 9.98006882e-02]
for epoch >> 1
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.2000784   0.20009964 -0.20019931]
for epoch >> 2
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.2000784   0.20009964 -0.10019931]
for epoch >> 3
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 2.00078400e-01  2.00099638e-01 -1.99311776e-04]
for epoch >> 4
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated 